In [1]:
import numpy as np
import pandas as pd
import logging
import os
import sys
import re
import shutil
import copy
from datetime import datetime, timedelta
from time import strptime
from sqlalchemy import create_engine
from dateutil.relativedelta import relativedelta
import pymssql
from openpyxl import load_workbook
import calendar


pd.options.display.max_columns = 150

# Read

In [2]:
data = pd.read_csv('./train.csv', encoding = 'big5')

In [49]:
data

日期  測站          測項     0     1     2     3     4     5     6  \
0       2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12   
1       2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
2       2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37   
3       2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1   
4       2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   
5       2014/1/1  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9   
6       2014/1/1  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8   
7       2014/1/1  豐原          O3    16    30    27    23    24    28    24   
8       2014/1/1  豐原        PM10    56    50    48    35    25    12     4   
9       2014/1/1  豐原       PM2.5    26    39    36    35    31    28    25   
10      2014/1/1  豐原    RAINFALL     0     0     0     0     0     0     0   
11      2014/1/1  豐原          RH    77    68    67    74    72    73    74   
12      2014/1/1  豐原         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5   
13      2014/1/1  豐原         THC     2     2     2   1.9   1.9   1.8   1.9   
14      2014/1/1  豐原       WD_HR    37    80    57    76   110   106   101   
15      2014/1/1  豐原  WIND_DIREC    35    79   2.4    55    94   116   106   
16      2014/1/1  豐原  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5   
17      2014/1/1  豐原       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2   
18      2014/1/2  豐原    AMB_TEMP    16    15    15    14    14    15    16   
19      2014/1/2  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
20      2014/1/2  豐原          CO  0.26  0.25  0.28  0.27  0.24  0.26  0.34   
21      2014/1/2  豐原        NMHC  0.06  0.05  0.06  0.05  0.05  0.07  0.09   
22      2014/1/2  豐原          NO   1.4   1.1   1.3     1   1.2   1.1   1.6   
23      2014/1/2  豐原         NO2   3.7   3.2   3.3   3.1   3.1   4.3   9.4   
24      2014/1/2  豐原         NOx     5   4.3   4.7   4.1   4.3   5.5    11   
25      2014/1/2  豐原          O3    39    38    39    39    34    31    30   
26      2014/1/2  豐原        PM10    49    34    31    16    18     8    16   
27      2014/1/2  豐原       PM2.5    21    23    30    30    22    18    13   
28      2014/1/2  豐原    RAINFALL     0     0     0     0     0     0     0   
29      2014/1/2  豐原          RH    65    66    70    71    70    67    59   
...          ...  ..         ...   ...   ...   ...   ...   ...   ...   ...   
4290  2014/12/19  豐原         NOx   8.8   7.5   8.5   8.2   8.6   9.3    18   
4291  2014/12/19  豐原          O3    30    33    30    34    37    36    24   
4292  2014/12/19  豐原        PM10    45    50    64    51    44    34    40   
4293  2014/12/19  豐原       PM2.5    14    16    13    14    21    19    23   
4294  2014/12/19  豐原    RAINFALL     0     0     0     0     0     0     0   
4295  2014/12/19  豐原          RH    71    70    71    70    70    71    69   
4296  2014/12/19  豐原         SO2  -0.2     2   2.1   2.2   2.3   2.5   2.8   
4297  2014/12/19  豐原         THC   1.9   1.9     2   1.9   1.9     2   2.1   
4298  2014/12/19  豐原       WD_HR   115   119   102   119    97    90    97   
4299  2014/12/19  豐原  WIND_DIREC   118   119   110   123   111    86   111   
4300  2014/12/19  豐原  WIND_SPEED   1.8   1.7   1.8     2   1.6   1.4   0.9   
4301  2014/12/19  豐原       WS_HR   1.5   1.4   1.3   1.9   1.3     1     1   
4302  2014/12/20  豐原    AMB_TEMP    14    14    14    14    14    14    14   
4303  2014/12/20  豐原         CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   
4304  2014/12/20  豐原          CO  0.21   0.2  0.17  0.17  0.16  0.14  0.15   
4305  2014/12/20  豐原        NMHC  0.06  0.09  0.05  0.06  0.05  0.04  0.03   
4306  2014/12/20  豐原          NO   1.4   1.6   1.3   0.3   0.3   0.5   0.3   
4307  2014/12/20  豐原         NO2   8.5   8.7   4.1   6.3   4.3     4   4.4   
4308  2014/12/20  豐原         NOx   9.9    10   5.4   6.6   4.6   4.5   4.8   
4309  2014/12/20  豐原          O3    

In [6]:
data[data=='NR'] = 0

In [ ]:
for i in

In [20]:
raw_data = data.iloc[:,3:].to_numpy()
raw_data

array([['14', '14', '14', ..., '15', '15', '15'],
       ['1.8', '1.8', '1.8', ..., '1.8', '1.8', '1.8'],
       ['0.51', '0.41', '0.39', ..., '0.35', '0.36', '0.32'],
       ...,
       ['36', '55', '72', ..., '118', '100', '105'],
       ['1.9', '2.4', '1.9', ..., '1.5', '2', '2'],
       ['0.7', '0.8', '1.8', ..., '1.6', '1.8', '2']], dtype=object)

In [35]:
month_data = {}
for month in range(12):
    sample = np.zeros([18, 20*24])
    for day in range(20):
        sample[:,day*24:(day+1)*24] = raw_data[(month*20 + day)*18:(month*20+day+1)*18,:]
    month_data[month] = sample

In [50]:
pd.DataFrame(month_data[1])

0       1       2       3       4       5      6      7      8    \
0    15.00   14.00   14.00   14.00   14.00   14.00  14.00  14.00  16.00   
1     1.80    1.80    1.70    1.80    1.70    1.70   1.70   1.70   1.80   
2     0.27    0.26    0.25    0.26    0.24    0.23   0.26   0.45   0.76   
3     0.05    0.05    0.04    0.05    0.05    0.05   0.05   0.13   0.22   
4     0.90    0.90    1.00    1.60    1.30    1.20   1.40   2.20   4.20   
5     4.80    4.40    3.90    2.40    2.80    2.70   3.30   9.10  16.00   
6     5.70    5.30    4.90    4.00    4.10    3.90   4.70  11.00  20.00   
7    45.00   45.00   45.00   43.00   41.00   41.00  41.00  31.00  28.00   
8    32.00   22.00   27.00   27.00   20.00   16.00   8.00   8.00  18.00   
9    30.00   32.00   36.00   29.00   16.00   10.00  23.00  27.00  33.00   
10    0.00    0.00    0.00    0.00    0.00    0.00   0.00   0.00   0.00   
11   63.00   61.00   62.00   63.00   63.00   60.00  57.00  58.00  56.00   
12    1.80    0.90    0.90    0.90    0.80    0.90   1.00   1.10   1.60   
13    1.80    1.80    1.80    1.80    1.80    1.80   1.80   1.90   2.00   
14  111.00  112.00  104.00  116.00  108.00  101.00  97.00  87.00  90.00   
15  113.00  109.00  104.00  119.00  105.00   80.00  82.00  89.00  47.00   
16    2.30    2.20    2.60    2.00    2.50    1.40   1.20   0.70   0.60   
17    2.50    2.20    2.20    2.00    1.80    1.70   1.30   0.80   0.40   

       9       10      11      12      13      14      15      16      17   \
0    20.00   22.00   23.00   24.00   24.00   24.00   23.00   23.00   22.00   
1     1.80    1.70    1.70    1.70    1.70    1.70    1.70    1.70    1.70   
2     0.56    0.33    0.30    0.27    0.26    0.25    0.24    0.24    0.33   
3     0.16    0.06    0.05    0.04    0.04    0.04    0.03    0.04    0.08   
4     4.30    2.80    2.10    2.10    2.00    1.70    1.70    1.70    1.60   
5    14.00    7.00    4.50    3.60    3.90    4.40    4.20    5.60    7.90   
6    18.00    9.80    6.60    5.70    5.90    6.10    5.90    7.40    9.50   
7    42.00   56.00   61.00   62.00   65.00   65.00   61.00   57.00   53.00   
8    29.00   43.00   52.00   48.00   37.00   32.00   36.00   36.00   36.00   
9    21.00   32.00   30.00   36.00   26.00   21.00   19.00   19.00   19.00   
10    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
11   44.00   38.00   41.00   38.00   38.00   41.00   43.00   46.00   49.00   
12    1.90    4.10    2.90    2.20    2.80    2.60    2.80    3.40    2.10   
13    1.90    1.80    1.80    1.80    1.80    1.80    1.70    1.80    1.80   
14  292.00  305.00  312.00  313.00  304.00  312.00  310.00  307.00  328.00   
15  293.00  311.00  314.00  305.00  300.00  314.00  317.00  306.00   51.00   
16    1.10    2.00    2.90    3.20    3.20    3.60    3.60    3.10    1.10   
17    0.50    1.30    2.10    2.10    2.10    3.10    2.80    2.10    0.40   

       18     19     20     21     22     23     24     25     26     27   \
0    19.00  18.00  19.00  18.00  17.00  19.00  18.00  17.00  18.00  18.00   
1     1.70   1.80   1.70   1.80   1.80   1.70   1.70   1.70   1.80   1.80   
2     0.40   0.43   0.33   0.51   0.37   0.33   0.30   0.25   0.31   0.28   
3     0.12   0.14   0.09   0.20   0.10   0.08   0.08   0.06   0.11   0.10   
4     1.60   1.60   1.80   1.80   1.80   1.80   1.90   1.60   1.70   0.70   
5    12.00  14.00  10.00  22.00  13.00   9.90   7.10   4.80   8.70   7.50   
6    13.00  16.00  12.00  23.00  14.00  12.00   9.00   6.40  10.00   8.20   
7    42.00  34.00  43.00  20.00  32.00  40.00  39.00  37.00  28.00  27.00   
8    48.00  61.00  61.00  57.00  42.00  43.00  37.00  45.00  30.00  17.00   
9    18.00  27.00  37.00  39.00  31.00  25.00  22.00  20.00  13.00   8.00   
10    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
11   56.00  61.00  57.00  63.00  64.00  59.00  61.00  66.00  65.00  63.00   
12    1.90   1.80   1.70   1.70   1.60   1.70   1.50   1.30   1.40   1.40   
13    1.90   1.90   

In [75]:
x = np.empty([12*471,9*18],dtype=float)
y = np.empty([12*471,1],dtype=float)

for month in range(12):
    for day in range(20):
        for hour in range(24):
            if day==19 and hour>14:
                continue
            x[month*12+day*20+hour,:] = month_data[month][:,(day*20+hour):(day*20+hour+9)].reshape(1,-1)
            y[month*12+day*20+hour,0] = month_data[month][9,day*20+hour+9]

In [80]:
print(x)
print(y)

[[14.  14.  14.  ...  2.   2.   0.5]
 [14.  14.  13.  ...  2.   0.5  0.3]
 [14.  13.  12.  ...  0.5  0.3  0.8]
 ...
 [17.  18.  19.  ...  1.1  1.4  1.3]
 [18.  19.  18.  ...  1.4  1.3  1.6]
 [19.  18.  17.  ...  1.3  1.6  1.8]]
[[30.]
 [41.]
 [44.]
 ...
 [17.]
 [24.]
 [29.]]


In [47]:
data

日期  測站          測項     0     1     2     3     4     5     6  \
0       2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12   
1       2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
2       2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37   
3       2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1   
4       2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   
5       2014/1/1  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9   
6       2014/1/1  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8   
7       2014/1/1  豐原          O3    16    30    27    23    24    28    24   
8       2014/1/1  豐原        PM10    56    50    48    35    25    12     4   
9       2014/1/1  豐原       PM2.5    26    39    36    35    31    28    25   
10      2014/1/1  豐原    RAINFALL     0     0     0     0     0     0     0   
11      2014/1/1  豐原          RH    77    68    67    74    72    73    74   
12      2014/1/1  豐原         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5   
13      2014/1/1  豐原         THC     2     2     2   1.9   1.9   1.8   1.9   
14      2014/1/1  豐原       WD_HR    37    80    57    76   110   106   101   
15      2014/1/1  豐原  WIND_DIREC    35    79   2.4    55    94   116   106   
16      2014/1/1  豐原  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5   
17      2014/1/1  豐原       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2   
18      2014/1/2  豐原    AMB_TEMP    16    15    15    14    14    15    16   
19      2014/1/2  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
20      2014/1/2  豐原          CO  0.26  0.25  0.28  0.27  0.24  0.26  0.34   
21      2014/1/2  豐原        NMHC  0.06  0.05  0.06  0.05  0.05  0.07  0.09   
22      2014/1/2  豐原          NO   1.4   1.1   1.3     1   1.2   1.1   1.6   
23      2014/1/2  豐原         NO2   3.7   3.2   3.3   3.1   3.1   4.3   9.4   
24      2014/1/2  豐原         NOx     5   4.3   4.7   4.1   4.3   5.5    11   
25      2014/1/2  豐原          O3    39    38    39    39    34    31    30   
26      2014/1/2  豐原        PM10    49    34    31    16    18     8    16   
27      2014/1/2  豐原       PM2.5    21    23    30    30    22    18    13   
28      2014/1/2  豐原    RAINFALL     0     0     0     0     0     0     0   
29      2014/1/2  豐原          RH    65    66    70    71    70    67    59   
...          ...  ..         ...   ...   ...   ...   ...   ...   ...   ...   
4290  2014/12/19  豐原         NOx   8.8   7.5   8.5   8.2   8.6   9.3    18   
4291  2014/12/19  豐原          O3    30    33    30    34    37    36    24   
4292  2014/12/19  豐原        PM10    45    50    64    51    44    34    40   
4293  2014/12/19  豐原       PM2.5    14    16    13    14    21    19    23   
4294  2014/12/19  豐原    RAINFALL     0     0     0     0     0     0     0   
4295  2014/12/19  豐原          RH    71    70    71    70    70    71    69   
4296  2014/12/19  豐原         SO2  -0.2     2   2.1   2.2   2.3   2.5   2.8   
4297  2014/12/19  豐原         THC   1.9   1.9     2   1.9   1.9     2   2.1   
4298  2014/12/19  豐原       WD_HR   115   119   102   119    97    90    97   
4299  2014/12/19  豐原  WIND_DIREC   118   119   110   123   111    86   111   
4300  2014/12/19  豐原  WIND_SPEED   1.8   1.7   1.8     2   1.6   1.4   0.9   
4301  2014/12/19  豐原       WS_HR   1.5   1.4   1.3   1.9   1.3     1     1   
4302  2014/12/20  豐原    AMB_TEMP    14    14    14    14    14    14    14   
4303  2014/12/20  豐原         CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   
4304  2014/12/20  豐原          CO  0.21   0.2  0.17  0.17  0.16  0.14  0.15   
4305  2014/12/20  豐原        NMHC  0.06  0.09  0.05  0.06  0.05  0.04  0.03   
4306  2014/12/20  豐原          NO   1.4   1.6   1.3   0.3   0.3   0.5   0.3   
4307  2014/12/20  豐原         NO2   8.5   8.7   4.1   6.3   4.3     4   4.4   
4308  2014/12/20  豐原         NOx   9.9    10   5.4   6.6   4.6   4.5   4.8   
4309  2014/12/20  豐原          O3    